# Generated by Django 5.2.1 on 2025-06-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_rename_description_asset_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.TextField(max_length=2048),
        ),
    ]
