# Generated by Django 5.2.1 on 2025-05-25 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateModel',
            new_name='AssetModel',
        ),
    ]
