# Generated by Django 5.2.1 on 2025-05-25 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0005_rename_createmodel_assetmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetmodel',
            old_name='done',
            new_name='available',
        ),
    ]
