# Generated by Django 5.2.1 on 2025-06-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0007_asset_delete_assetmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
